name: renovate_reproduction_26319
environment:
  sdk: ^3.9.0

dependencies:
  example_git_package:
    git:
      url: https://github.com/Conrad598/renovate-reproduction-26319
      tag_pattern: "{{version}}"
      path: ./example_git_package
    version: ^1.0.0
