name: renovate_reproduction_26319
environment:
  sdk: ^3.9.0

dependencies:
  archive:
    git:
      url: https://github.com/brendan-duncan/archive
      tag_pattern: "{{version}}"
    version: ^3.0.0
  
